#!/usr/bin/env python3
"""Generate the consolidated decision register and subfeature index referenced by docs/13.

Usage: python3 tools/build_registers.py
Writes:
  docs/13a-decision-register.generated.md
  docs/13b-subfeature-index.generated.md  (via check_catalogue.py --index)
"""
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
ROW = re.compile(r"^\|\s*\**(D-\d{3})\**\s*\|(.*)$")


def decision_rows():
    files = sorted(glob.glob(os.path.join(DOCS, "*.md")) + glob.glob(os.path.join(DOCS, "01-catalogue", "*.md")))
    rows = {}
    for path in files:
        rel = os.path.relpath(path, DOCS)
        if rel.startswith("13a-") or rel.startswith("13b-"):
            continue
        for line in open(path, encoding="utf-8"):
            m = ROW.match(line.rstrip("\n"))
            if not m:
                continue
            cells = [c.strip() for c in m.group(2).strip().strip("|").split("|")]
            rows.setdefault(m.group(1), (rel, cells))
    return rows


def main():
    rows = decision_rows()
    out = os.path.join(DOCS, "13a-decision-register.generated.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# Consolidated decision register (generated)\n\n")
        fh.write("> Generated by `tools/build_registers.py` from every `| D-nnn |` table row in docs/. "
                 "Do not edit by hand; edit the source row. Column order in the source tables is "
                 "typically *decision | interim assumption | owner* (or *owner | interim assumption*); "
                 "the source file is authoritative for detail.\n\n")
        fh.write(f"Total decisions: **{len(rows)}**\n\n")
        fh.write("| Id | Source | Decision / interim assumption / owner |\n|---|---|---|\n")
        for did in sorted(rows):
            rel, cells = rows[did]
            text = " • ".join(c for c in cells if c)
            if len(text) > 400:
                text = text[:397] + "..."
            fh.write(f"| {did} | `{rel}` | {text} |\n")
    print(f"wrote {out} ({len(rows)} decisions)")
    rc = subprocess.call([sys.executable, os.path.join(ROOT, "tools", "check_catalogue.py"),
                          "--index", os.path.join(DOCS, "13b-subfeature-index.generated.md")])
    return rc


if __name__ == "__main__":
    sys.exit(main())
