#!/usr/bin/env python3
"""Phase 1 planning-gate checks for the MetriStay module catalogue (master prompt Section M).

Parses every ```yaml block in docs/01-catalogue/*.md, validates Section-L fields,
and optionally writes the generated subfeature index used by docs/13.

Usage:
  python3 tools/check_catalogue.py            # print report, exit 1 on failure
  python3 tools/check_catalogue.py --index docs/13-traceability-index.generated.md
"""
import glob
import os
import re
import sys
from collections import Counter, defaultdict

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGUE = os.path.join(ROOT, "docs", "01-catalogue")
REQUIRED = [
    "id", "name", "phase", "release", "actors", "screens", "inputs", "states", "api",
    "events", "data", "rules", "security", "failure_cases", "finance_report_effect",
    "i18n_a11y", "acceptance", "dependency",
]
ID_RE = re.compile(r"^M(\d{2})\.F(\d{2})\.(\d+)\.SF\2\.\3\.(\d+)$")
BLOCK_RE = re.compile(r"^```yaml\s*\n(.*?)^```", re.M | re.S)


def iter_records(obj):
    if isinstance(obj, dict):
        if "id" in obj and "name" in obj:
            yield obj
        else:
            for v in obj.values():
                yield from iter_records(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from iter_records(v)


def load():
    records, errors = [], []
    for path in sorted(glob.glob(os.path.join(CATALOGUE, "*.md"))):
        text = open(path, encoding="utf-8").read()
        for m in BLOCK_RE.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            try:
                data = yaml.safe_load(m.group(1))
            except yaml.YAMLError as exc:
                errors.append(f"{os.path.basename(path)}:{line}: YAML error: {exc}")
                continue
            for rec in iter_records(data):
                if str(rec.get("id", "")).startswith("M"):
                    rec["_file"] = os.path.basename(path)
                    rec["_line"] = line
                    records.append(rec)
    return records, errors


def is_empty(v):
    return v is None or (isinstance(v, (str, list, dict)) and len(v) == 0)


def main():
    records, errors = load()
    seen = Counter(r["id"] for r in records)
    for sid, n in seen.items():
        if n > 1:
            errors.append(f"duplicate id {sid} ({n}x)")
    by_module = defaultdict(list)
    for r in records:
        m = ID_RE.match(str(r["id"]))
        if not m:
            errors.append(f"{r['_file']}:{r['_line']}: malformed id {r['id']}")
            continue
        by_module[int(m.group(1))].append(r)
        for f in REQUIRED:
            if f not in r or is_empty(r[f]):
                errors.append(f"{r['_file']}:{r['_line']}: {r['id']} missing/empty field '{f}'")
        if str(r.get("release")) not in ("R1", "Later"):
            errors.append(f"{r['id']}: release must be R1|Later, got {r.get('release')}")
        try:
            ph = int(str(r.get("phase")).split()[0].split("/")[0].split("-")[0].split("–")[0])
            if not 2 <= ph <= 8:
                raise ValueError
        except ValueError:
            errors.append(f"{r['id']}: phase must start with 2..8, got {r.get('phase')}")

    missing = [m for m in range(1, 69) if m not in by_module]
    for m in missing:
        errors.append(f"module M{m:02d} has no subfeatures")

    print(f"subfeatures: {len(records)}  modules: {len(by_module)}  "
          f"features: {len({str(r['id']).split('.SF')[0] for r in records})}")
    print(f"release R1: {sum(1 for r in records if r.get('release') == 'R1')}  "
          f"Later: {sum(1 for r in records if r.get('release') == 'Later')}")

    if "--index" in sys.argv:
        out = sys.argv[sys.argv.index("--index") + 1]
        with open(out, "w", encoding="utf-8") as fh:
            fh.write("# Generated subfeature traceability index\n\n")
            fh.write("> Generated by `tools/check_catalogue.py --index`. Do not edit by hand.\n\n")
            fh.write("| SF id | Name | Phase | Release | Acceptance | Source |\n|---|---|---|---|---|---|\n")
            for m in sorted(by_module):
                for r in sorted(by_module[m], key=lambda x: [int(p) if p.isdigit() else p
                                                             for p in re.split(r"[.F]", str(x["id"]).split("SF")[1])]):
                    acc = str(r.get("acceptance", "")).replace("|", "/").replace("\n", " ")
                    if len(acc) > 160:
                        acc = acc[:157] + "..."
                    name = str(r["name"]).replace("|", "/")
                    fh.write(f"| {r['id']} | {name} | {r.get('phase')} | {r.get('release')} | {acc} | "
                             f"`01-catalogue/{r['_file']}` |\n")
        print(f"wrote {out}")

    if errors:
        print(f"\n{len(errors)} problem(s):")
        for e in errors[:200]:
            print("  -", e)
        return 1
    print("OK: all Section M catalogue checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
